### ISSUE TITLE
License

### ISSUE THREAD

**Issue by erik-am** [p3pijn/SIGGuidelines.Analyzers#2]
The license currently makes it hard for our company to use this extension.
Could you consider changing the license to MIT or to LGPL?

**Comment by MichielCuijpers** [comment]
Hi Erik, i would like to contact you on this matter, we currently talking to a person at your company. (Where) Can I call you? groet Michiel

**Comment by erik-am** [comment]
[ removed telephone number, as call took place ]

**Comment by p3pijn** [comment]
Hi Erik,
New versions of this package will be distributed under the Lesser GPL licence v3.

**Comment by erik-am** [comment]
Great, thank you! :smile:  :+1:
